language: python
python:
  - "3.7"
# command to install dependencies
install:
  - python3 -m pip install --upgrade pip setuptools
  - pip install -r requirements.txt
script:
  - python -c 'print("add scripts here")'
 
